import type { Metadata } from "next"
import "./globals.css"
import '../../public/runtime.css'
import defaultTheme from '../../default-theme.json'
import { replacePlaceholders } from "@/services/StyleService"
import { ThemeProvider } from "@/context/ThemeContext"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const updatedConfig = replacePlaceholders(defaultTheme);
  return (
    <html lang="en">
      <body>
        <ThemeProvider config={updatedConfig}>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}

